// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: grpcscorerprotos/grpcscorer.proto

package grpcscorerprotos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScoreRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MatchId string `protobuf:"bytes,1,opt,name=matchId,proto3" json:"matchId,omitempty"`
}

func (x *ScoreRequest) Reset() {
	*x = ScoreRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcscorerprotos_grpcscorer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreRequest) ProtoMessage() {}

func (x *ScoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcscorerprotos_grpcscorer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreRequest.ProtoReflect.Descriptor instead.
func (*ScoreRequest) Descriptor() ([]byte, []int) {
	return file_grpcscorerprotos_grpcscorer_proto_rawDescGZIP(), []int{0}
}

func (x *ScoreRequest) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

type ScoreResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MatchId      string `protobuf:"bytes,1,opt,name=matchId,proto3" json:"matchId,omitempty"`
	CurrentScore string `protobuf:"bytes,2,opt,name=currentScore,proto3" json:"currentScore,omitempty"`
}

func (x *ScoreResponse) Reset() {
	*x = ScoreResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcscorerprotos_grpcscorer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreResponse) ProtoMessage() {}

func (x *ScoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcscorerprotos_grpcscorer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreResponse.ProtoReflect.Descriptor instead.
func (*ScoreResponse) Descriptor() ([]byte, []int) {
	return file_grpcscorerprotos_grpcscorer_proto_rawDescGZIP(), []int{1}
}

func (x *ScoreResponse) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *ScoreResponse) GetCurrentScore() string {
	if x != nil {
		return x.CurrentScore
	}
	return ""
}

var File_grpcscorerprotos_grpcscorer_proto protoreflect.FileDescriptor

var file_grpcscorerprotos_grpcscorer_proto_rawDesc = []byte{
	0x0a, 0x21, 0x67, 0x72, 0x70, 0x63, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x72, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x67, 0x6f, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x72, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x22, 0x28, 0x0a, 0x0c, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x49, 0x64, 0x22, 0x4d, 0x0a,
	0x0d, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x75, 0x72, 0x72,
	0x65, 0x6e, 0x74, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x32, 0xa3, 0x01, 0x0a,
	0x06, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x72, 0x12, 0x49, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x53, 0x63,
	0x6f, 0x72, 0x65, 0x12, 0x1c, 0x2e, 0x67, 0x6f, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x72, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1d, 0x2e, 0x67, 0x6f, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x72, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x2e, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x4e, 0x0a, 0x0b, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x53, 0x63, 0x6f, 0x72,
	0x65, 0x12, 0x1c, 0x2e, 0x67, 0x6f, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x72, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x2e, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1d, 0x2e, 0x67, 0x6f, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x72, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x2e, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x30, 0x01, 0x42, 0x41, 0x5a, 0x3f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x6d, 0x65, 0x73, 0x73, 0x78, 0x2f, 0x67, 0x6f, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x70,
	0x6c, 0x61, 0x79, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x73, 0x63,
	0x6f, 0x72, 0x65, 0x72, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x72, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpcscorerprotos_grpcscorer_proto_rawDescOnce sync.Once
	file_grpcscorerprotos_grpcscorer_proto_rawDescData = file_grpcscorerprotos_grpcscorer_proto_rawDesc
)

func file_grpcscorerprotos_grpcscorer_proto_rawDescGZIP() []byte {
	file_grpcscorerprotos_grpcscorer_proto_rawDescOnce.Do(func() {
		file_grpcscorerprotos_grpcscorer_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpcscorerprotos_grpcscorer_proto_rawDescData)
	})
	return file_grpcscorerprotos_grpcscorer_proto_rawDescData
}

var file_grpcscorerprotos_grpcscorer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_grpcscorerprotos_grpcscorer_proto_goTypes = []interface{}{
	(*ScoreRequest)(nil),  // 0: goscorerprotos.ScoreRequest
	(*ScoreResponse)(nil), // 1: goscorerprotos.ScoreResponse
}
var file_grpcscorerprotos_grpcscorer_proto_depIdxs = []int32{
	0, // 0: goscorerprotos.Scorer.GetScore:input_type -> goscorerprotos.ScoreRequest
	0, // 1: goscorerprotos.Scorer.StreamScore:input_type -> goscorerprotos.ScoreRequest
	1, // 2: goscorerprotos.Scorer.GetScore:output_type -> goscorerprotos.ScoreResponse
	1, // 3: goscorerprotos.Scorer.StreamScore:output_type -> goscorerprotos.ScoreResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpcscorerprotos_grpcscorer_proto_init() }
func file_grpcscorerprotos_grpcscorer_proto_init() {
	if File_grpcscorerprotos_grpcscorer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpcscorerprotos_grpcscorer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScoreRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcscorerprotos_grpcscorer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScoreResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpcscorerprotos_grpcscorer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpcscorerprotos_grpcscorer_proto_goTypes,
		DependencyIndexes: file_grpcscorerprotos_grpcscorer_proto_depIdxs,
		MessageInfos:      file_grpcscorerprotos_grpcscorer_proto_msgTypes,
	}.Build()
	File_grpcscorerprotos_grpcscorer_proto = out.File
	file_grpcscorerprotos_grpcscorer_proto_rawDesc = nil
	file_grpcscorerprotos_grpcscorer_proto_goTypes = nil
	file_grpcscorerprotos_grpcscorer_proto_depIdxs = nil
}
